import os
import re
import pandas as pd

# Load excel sheet for LONG01
excel_path = "UPGRADE YOUR ILETS SKILLS.xlsx"
try:
    df = pd.read_excel(excel_path, sheet_name="HV_LONG01", header=1)
except Exception as e:
    print("Error reading excel:", e)
    exit(1)

# Get all lesson names from columns 3, 13, 23 (0-indexed) -> D, N, X
# In pandas, if header=1 (row 2), then index 3 is the 4th column.
valid_lessons = set()
for col_idx in [3, 13, 23]:
    if col_idx < len(df.columns):
        for val in df.iloc[:, col_idx].dropna():
            name = str(val).replace("✅ ", "").strip()
            norm = re.sub(r'[^a-zA-Z0-9]', '', name).lower()
            if norm:
                valid_lessons.add(norm)

print(f"Loaded {len(valid_lessons)} valid lessons from Excel.")

# We will collect all lessonIds generated by the frontend
generated_lessons = []

# 1. Reading_1232_Basic
base_dir = "Reading_1232_Basic/frontend/data"
for root, dirs, files in os.walk(base_dir):
    for file in files:
        if file.endswith('.js'):
            # The URL parameter `file` is e.g. A1-A2/lesson_001.js
            # The frontend generates: "Reading " + parts[0] + " - " + parts[1].replace('.js', '')
            folder = os.path.basename(root)
            lessonId = f"Reading {folder} - {file.replace('.js', '')}"
            generated_lessons.append(lessonId)

# 2. Listening_102_Basic
base_dir2 = "Listening_102_Basic"
# The template uses lessonId: '{{TITLE}}' where TITLE is usually the folder name or HTML name
# In Listening_102_Basic, let's see how many folders or HTML files there are.
for root, dirs, files in os.walk(base_dir2):
    for file in files:
        if file.endswith('.html') and file != 'template.html':
            # E.g. Listening_102_Basic/Lesson_1/Lesson_1.html ?
            # Wait, usually the HTML contains the string. Let's read the file and extract lessonId: '...'
            path = os.path.join(root, file)
            with open(path, 'r', encoding='utf-8') as f:
                content = f.read()
                match = re.search(r"lessonId:\s*['\"]([^'\"]+)['\"]", content)
                if match:
                    generated_lessons.append(match.group(1))

# Check how many generated lessons exist in the Excel valid_lessons
matched = 0
unmatched = []

for lesson in generated_lessons:
    norm = re.sub(r'[^a-zA-Z0-9]', '', lesson).lower()
    if norm in valid_lessons:
        matched += 1
    else:
        unmatched.append(lesson)

print(f"Total generated lessons parsed: {len(generated_lessons)}")
print(f"Matched with Excel: {matched}")
print(f"Unmatched: {len(unmatched)}")
if unmatched:
    print("Sample unmatched:", unmatched[:20])

